# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iTqtrKl3ar5cZNNQC_4IBmtEG3-7ZGQq
"""



import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

diabities_dataset=pd.read_csv('/content/diabetes.csv')

print(diabities_dataset)

diabities_dataset.head()

diabities_dataset.shape

diabities_dataset.isnull().sum()
#so we see the dataset has no null values

X=diabities_dataset.drop('Outcome',axis=1)
Y=diabities_dataset['Outcome']

#As we see that the range of data is varying we need to standardise the data
standard=StandardScaler()
X=standard.fit_transform(X)

print(X)
print(Y)

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=4)

model=svm.SVC()

model.fit(X_train,Y_train)

Y_predict=model.predict(X_test)

print(Y_predict)

val=accuracy_score(Y_test,Y_predict)
print(val)

knn_classifier=KNeighborsClassifier(n_neighbors=3)
knn_classifier.fit(X_train,Y_train)
KNN_predict=knn_classifier.predict(X_test)

knn_accuracy=accuracy_score(Y_test,KNN_predict)
print(knn_accuracy)